" Minimal project-local Vim profile generated by cppboot.
" Load with :set exrc secure in your global vimrc.

set nocompatible
set encoding=utf-8
set fileformat=unix

" Indentation aligned with common C++ / Microsoft-format habits.
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set autoindent
set smartindent

" UX
set number
set relativenumber
set ruler
set showcmd
set wildmenu
set incsearch
set hlsearch
set ignorecase
set smartcase

" ctags: search upward for tags; regenerate with :make tags
set tags=./tags;,tags
nnoremap <leader>c :make tags<CR>

" Prefer repo-root compile_commands.json for ALE/coc/clangd integrations.
let g:cppboot_project_root = expand('<sfile>:p:h')

" Use the project Makefile as the default build command.
set makeprg=make
nnoremap <leader>m :make<CR>
nnoremap <leader>t :make test<CR>
nnoremap <leader>f :make fmt<CR>
