#!/usr/bin/env python3
"""Generate src/http/detail/mozilla_ca_bundle.cpp from data/cacert.pem.

Usage:
  python3 scripts/embed_cacert.py [--input data/cacert.pem] [--output src/http/detail/mozilla_ca_bundle.cpp]

The PEM is embedded as adjacent raw-string chunks (each well under 64KiB) so
-Woverlength-strings stays clean under -Werror.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import pathlib
import re
import sys


def extract_bundle_date(pem: str) -> str:
    """Parse 'Certificate data from Mozilla as of: ...' if present."""
    m = re.search(
        r"Certificate data from Mozilla as of:\s*(.+)",
        pem,
        re.IGNORECASE,
    )
    if not m:
        return "unknown"
    return m.group(1).strip()


def generate_cpp(pem: str, input_path: pathlib.Path) -> str:
    delim = "MOG_CA"
    if f"){delim}\"" in pem or f"){delim}" in pem:
        raise SystemExit("PEM contains raw-string delimiter; refuse to embed")

    bundle_date = extract_bundle_date(pem)
    sha256 = hashlib.sha256(pem.encode("utf-8")).hexdigest()
    generated = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    size = len(pem.encode("utf-8"))

    pem_lf = pem.replace("\r\n", "\n").replace("\r", "\n")
    if not pem_lf.endswith("\n"):
        pem_lf += "\n"

    try:
        rel = input_path.resolve().relative_to(pathlib.Path(__file__).resolve().parents[1])
        source_display = rel.as_posix()
    except ValueError:
        source_display = input_path.as_posix()

    # Keep each raw-string literal under 64KiB. Clang still flags *concatenated*
    # literals used as a single array initializer, so we assemble chunks once at
    # runtime into a static buffer instead of relying on compile-time concat.
    chunk_size = 12000
    parts: list[str] = []
    for i in range(0, len(pem_lf), chunk_size):
        piece = pem_lf[i : i + chunk_size]
        parts.append(f'    R"{delim}({piece}){delim}",')
    chunks_joined = "\n".join(parts)
    pem_len = len(pem_lf.encode("utf-8"))

    return f"""/**
 * @file mozilla_ca_bundle.cpp
 * @brief Embedded Mozilla CA root bundle (curl cacert.pem format).
 *
 * AUTO-GENERATED by scripts/embed_cacert.py — do not edit by hand.
 * Source: {source_display}
 * Bundle date: {bundle_date}
 * SHA-256: {sha256}
 * Generated (UTC): {generated}
 * Size: {size} bytes
 */

#include "http/detail/mozilla_ca_bundle.hpp"

#include <cstddef>
#include <cstring>

namespace mog::detail
{{
namespace
{{

// Each chunk is an independent string literal (avoids -Woverlength-strings).
constexpr std::string_view kChunks[] = {{
{chunks_joined}
}};

constexpr std::size_t kPemSize = {pem_len};

const char *AssembledPem() noexcept
{{
    static const char *ptr = []() noexcept -> const char * {{
        static char buf[kPemSize + 1];
        std::size_t off = 0;
        for (const std::string_view chunk : kChunks)
        {{
            if (off + chunk.size() > kPemSize)
            {{
                return nullptr;
            }}
            std::memcpy(buf + off, chunk.data(), chunk.size());
            off += chunk.size();
        }}
        buf[off] = '\\0';
        return off == kPemSize ? buf : nullptr;
    }}();
    return ptr;
}}

}} // namespace

std::string_view EmbeddedMozillaCaPem() noexcept
{{
    const char *p = AssembledPem();
    if (p == nullptr)
    {{
        return {{}};
    }}
    return std::string_view{{p, kPemSize}};
}}

std::string_view EmbeddedMozillaCaBundleDate() noexcept
{{
    return "{bundle_date}";
}}

std::string_view EmbeddedMozillaCaSha256() noexcept
{{
    return "{sha256}";
}}

}} // namespace mog::detail
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = pathlib.Path(__file__).resolve().parents[1]
    parser.add_argument(
        "--input",
        type=pathlib.Path,
        default=root / "data" / "cacert.pem",
        help="Path to cacert.pem (Mozilla via curl)",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=root / "src" / "http" / "detail" / "mozilla_ca_bundle.cpp",
        help="Generated C++ path",
    )
    args = parser.parse_args(argv)

    if not args.input.is_file():
        print(f"error: input not found: {args.input}", file=sys.stderr)
        return 1

    pem = args.input.read_text(encoding="utf-8")
    if "BEGIN CERTIFICATE" not in pem:
        print("error: input does not look like a PEM CA bundle", file=sys.stderr)
        return 1

    cpp = generate_cpp(pem, args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(cpp, encoding="utf-8")
    print(f"wrote {args.output} ({len(pem)} chars PEM, {cpp.count(chr(10))+1} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
